# Generated by Django 6.0.6 on 2026-07-13 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_resume_filename_profile_resume_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='personal_statement',
            field=models.TextField(blank=True),
        ),
    ]
