import type { Metadata } from "next";
import LegalLayout from "@/components/LegalLayout";

export const metadata: Metadata = {
  title: "Terms of Service — Briefcase",
  description: "The terms governing your use of Briefcase.",
};

export default function TermsPage() {
  return (
    <LegalLayout title="Terms of Service" updated="July 13, 2026">
      <p>
        These Terms of Service (&quot;Terms&quot;) govern your access to and use of Briefcase at
        briefcasecareer.com and its related services (the &quot;Service&quot;), operated by [YOUR
        LEGAL ENTITY] (&quot;Briefcase,&quot; &quot;we,&quot; &quot;us&quot;). By creating an account
        or using the Service, you agree to these Terms. If you do not agree, do not use the Service.
      </p>

      <h2>Eligibility and accounts</h2>
      <p>
        You must be at least 16 years old to use the Service. You are responsible for the activity
        under your account and for keeping your login credentials secure. Provide accurate information
        and keep it up to date.
      </p>

      <h2>The Service</h2>
      <p>
        Briefcase lets you store a bank of your career experience and uses AI to generate tailored
        cover letters, resumes, keyword analysis, and fit scores for job postings you provide. We may
        add, change, or remove features over time.
      </p>

      <h2>Your content</h2>
      <p>
        You retain ownership of the content you provide, including your experience bank, uploaded
        resumes, and pasted job descriptions (&quot;Your Content&quot;). You grant us a limited
        license to store and process Your Content, and to transmit it to our AI and infrastructure
        providers, solely to operate and provide the Service to you. You are responsible for having
        the right to submit Your Content and for ensuring it is accurate.
      </p>

      <h2>AI-generated content</h2>
      <p>
        Documents generated by the Service are produced by AI and may contain errors, omissions, or
        inaccuracies. They are drafts to assist you, not final work product. You are solely
        responsible for reviewing, editing, and verifying any generated content before you use or
        submit it to an employer or third party. The Service does not provide legal, career, or
        professional advice, and we make no guarantee of any particular outcome, including employment.
      </p>

      <h2>Acceptable use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>Use the Service for any unlawful, fraudulent, or misleading purpose.</li>
        <li>Submit content that infringes others&apos; rights or that you have no right to submit.</li>
        <li>Attempt to disrupt, overload, reverse engineer, or gain unauthorized access to the Service.</li>
        <li>Use automated means to abuse the Service or exceed applicable rate limits.</li>
        <li>Misrepresent your identity, experience, or qualifications to third parties.</li>
      </ul>

      <h2>Fees</h2>
      <p>
        Portions of the Service may be offered free of charge, and we may introduce paid plans in the
        future. If you purchase a paid plan, the applicable pricing and billing terms will be
        presented to you at the time of purchase.
      </p>

      <h2>Third-party services</h2>
      <p>
        The Service relies on third-party providers (including Clerk, OpenAI, Railway, and Vercel).
        Your use of the Service is also subject to those providers&apos; terms where applicable. We
        are not responsible for third-party services.
      </p>

      <h2>Disclaimers</h2>
      <p>
        The Service is provided &quot;as is&quot; and &quot;as available,&quot; without warranties of
        any kind, whether express or implied, including fitness for a particular purpose,
        merchantability, and non-infringement. We do not warrant that the Service will be
        uninterrupted, error-free, or secure, or that generated content will be accurate or suitable.
      </p>

      <h2>Limitation of liability</h2>
      <p>
        To the maximum extent permitted by law, Briefcase and its operators will not be liable for
        any indirect, incidental, special, consequential, or punitive damages, or any loss of data,
        opportunities, or profits, arising from your use of the Service. Our total liability for any
        claim relating to the Service will not exceed the greater of the amount you paid us in the
        twelve months before the claim or USD 100.
      </p>

      <h2>Indemnification</h2>
      <p>
        You agree to indemnify and hold harmless Briefcase from any claims, damages, or expenses
        arising out of Your Content or your violation of these Terms or applicable law.
      </p>

      <h2>Termination</h2>
      <p>
        You may stop using the Service and delete your account at any time. We may suspend or
        terminate your access if you violate these Terms or if necessary to protect the Service or
        other users. Provisions that by their nature should survive termination will survive.
      </p>

      <h2>Changes to these Terms</h2>
      <p>
        We may update these Terms from time to time. When we do, we will revise the &quot;Last
        updated&quot; date above. Your continued use of the Service after changes take effect
        constitutes acceptance of the updated Terms.
      </p>

      <h2>Governing law</h2>
      <p>
        These Terms are governed by the laws of [JURISDICTION], without regard to its conflict of laws
        rules. Any disputes will be resolved in the courts located in [JURISDICTION].
      </p>

      <h2>Contact</h2>
      <p>
        Questions about these Terms? Contact us at{" "}
        <a href="mailto:support@briefcasecareer.com">support@briefcasecareer.com</a>.
      </p>
    </LegalLayout>
  );
}
