# Generated by Django 6.0.6 on 2026-07-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience_bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experienceentry',
            name='type',
            field=models.CharField(choices=[('job', 'Job'), ('project', 'Project'), ('certification', 'Certification'), ('education', 'Education')], max_length=20),
        ),
    ]
