# Generated by Django 6.0.6 on 2026-07-13 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience_bank', '0002_alter_experienceentry_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='experienceentry',
            name='completed',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
