# Generated by Django 6.0.6 on 2026-07-01 16:25

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('job_description', models.TextField()),
                ('job_description_embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('generated_cover_letters', models.JSONField(blank=True, default=dict)),
                ('selected_variant', models.CharField(blank=True, max_length=20)),
                ('tailored_resume', models.JSONField(blank=True, default=dict)),
                ('match_score', models.FloatField(blank=True, null=True)),
                ('keyword_gap_analysis', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('interview', 'Interview'), ('rejected', 'Rejected'), ('offer', 'Offer')], default='applied', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='accounts.profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
